juma_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("codage/", views.codage, name="codage"),
    path("webdesign/", views.webdesign, name="webdesign"),
    path("intropython/", views.intropython, name="intropython"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("education/", views.education, name="education"),
    path("translate/", views.translate, name="translate"),
    path("training/", views.training, name="training"),
    path("workshop/", views.workshop, name="workshop"),
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render
from django.utils.translation import ugettext as _  # pour test langue


def home(request):
    return render(request, "pages/home.html", {})


def codage(request):
    return render(request, "pages/codage.html", {})


def webdesign(request):
    return render(request, "pages/webdesign.html", {})


def intropython(request):
    return render(request, "pages/intropython.html", {})


def about(request):
    return render(request, "pages/about.html", {})


def contact(request):
    return render(request, "pages/contact.html", {})


def education(request):
    return render(request, "pages/education.html", {})


def translate(request):
    return render(request, "pages/translate.html", {})


def training(request):
    return render(request, "pages/training.html", {})


def workshop(request):
    return render(request, "pages/workshop.html", {})

templates/pages/about.html
{% extends 'pages/base.html' %} {% load static %} {% block body %}
<!-- Main page -->
<div class="container">

    <section class="about-us">
        <div class="about-us___intro">
            <img src="{{ MEDIA_URL }}/marlene400x300.png" %} " class="marleneimg ">
            <h4>Dr. Marlene Marchena <br> </h4>
            <p>Principal Trainer</p>
            </div>
        <div class="about-us__body ">
            <p><strong>Marlene Marchena</strong> is a data analysis and Python/R developer. 
                She graduated in Economics and holds a Ph.D. in Electrical Engineering.
                She has a domain expertice in the fields os credit risk and supply chain 
                management.
                Currently she is doing an specialization in Data Science at ULB university.
            </p>    
            <p> 
                Marlene works as a computer science educator. She likes to share her passion 
                about technology by teaching and given training. She has experience teaching kids and adults.

                 

            </p>

        </div>
    </section>
</div>
{% endblock %}
 She has experience teaching programming to kids and adults.

templates/pages/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8"> {% load static %} {% load i18n %}
    <!-- copied from imar responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> {% block head %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <title>Jumahes</title>
    {% endblock %}
    <!-- Custom styles for this template -->
    <link href="{% static 'pages/css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'pages/css/icons.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'pages/js/myjs.js' %}"></script>
</head>

<body>
    <header>
        <div class="wrapper">
            <div class="top-nav">
                <!-- <div class="top2right"> -->
                <div class="languages-dropdown">
                    <button class="language-btn">
                        <!-- <button class="language-btn">     -->

                </button>
                    <div class="languages-dropdown-content">
                       
                        <ul>
                            <form action="" method="post">
                                {% csrf_token %}
                                <input name="next" type="hidden" value="{{ request.get_full_path }}" />
                                <input name="language" type="hidden" value="{{ language.code }}" />
                                <div class="dropdown-item"><input class="dropdown-item" type="submit" value="{{ language.name_local }} ({{ language.code }}) {% if language.code == LANGUAGE_CODE %}✓{% endif %}" />
                            </form>
                        </ul>

                        </div>
                    </div>
                </div>

                <!-- </div> -->
                <!-- <div class="container"> -->
                <!-- <img src="{{ MEDIA_URL }}/logo100x300.png" class="logo"> -->
                <h1 class="logo">
                    <a href="{% url 'pages:home' %}">Jumahes</a>
                    <!-- <img src="{{ MEDIA_URL }}/logo100x300.png"> -->
                </h1>
                <nav>
                    <ul>
                        <li><a href="{% url 'pages:home' %}">HOME</a></li>
                        <li><a href="{% url 'pages:about' %}">ABOUT</a></li>
                        <li class="dropdown"><a href="#">SERVICES<span class="icon-caret-down"></span></a>
                            <div class="dropdown-content">
                                <a href="{% url 'pages:education' %}"><span class="icon-dot-single"></span>Education</a>
                                <a href="{% url 'pages:training' %}"><span class="icon-dot-single"></span>Training</a>
                                <a href="{% url 'pages:workshop' %}"><span class="icon-dot-single"></span>Workshops</a>
                            </div>
                        </li>
                        <li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
                    </ul>
                </nav>
                <!-- </div> -->

            </div>
    </header>

    {% block body %}
    <div>
        <div>

            <h1>Marlene Marchena</h1>
            <p>
                Aqui mi texto <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a> for you, for free. You can replace all this text with your own text. You can remove any link to our website from this website template, you're free
                to use this website template without linking back to us. If you're having problems editing this website template, then don't hesitate to ask for help on the <a href="http://www.freewebsitetemplates.com/forums/">Forums</a>.
            </p>
        </div>
    </div>
    {% endblock %}
    <!-- Footer-->
    <footer>
        <p class="m-0 text-center text-white">Copyright &copy; Jumahes 2020. All Rights Reserved.</p>
    </footer>

</body>

</html>

templates/pages/codage.html
{% extends 'pages/base.html' %} {% load static %} {% block body%}

<div class="container">
    <section>
        <h2>Why learn to code?</h2>
        <p>
            Computers are part of our everyday life, we use them to surf the internet, do a Google search, see pictures, read e-mails, play games or write text. But how they do all of this? Is it magic? Yes, it's magic. A magic called coding (or programming). Learning
            to code is not about vocation but a skill necessary to understand how our world works.
        </p>
        <p>
            Now days learn to code is not about vocation but a required skill in order to understand how our world works.
        </p>

        <h2>Positive aspects</h2>
        <p>
            Programming is an activity that stimulates creativity, promotes collaboration, develops rigor, patience and perseverance. It trains a logical thinking to solve problems.
        </p>
        <h2>Methodology</h2>
        <p>
            In a fun and enjoyable way you will become familiar with the basic concepts of coding: variables, loops, conditions, etc. We will make you discover different interfaces based on visual blocks where you can create animations, mini-games or your own stories.
        </p>
    </section>
</div>
{% endblock %}

templates/pages/contact.html
{% extends 'pages/base.html' %} {% load static %} {% block body%}

<div class="container">
    <section>
        <h2 class="section-title">Contact Us</h2>
        <!-- <div class="col-md-3 mb-5"> -->
        <hr>
        <address>
          <strong>Jumahes</strong>
          <br>Etterbeek, Brussels
          <br>Belgium
        </address>
        <address>
          <!-- <abbr title="Phone">P:</abbr>
          (32) 456-7890
          <br> -->
          <abbr title="Email">E:</abbr>
          <a href="mailto:#">info@jumahes.com</a>
        </address>
        <!-- </div> -->
    </section>
</div>
{% endblock %}

templates/pages/education.html
 {% extends 'pages/base.html' %} {% load static %} {% load i18n %} {% block body %}
<!-- Main page -->
<div class="container">
    <hr>
    <div class="row justify-content-center">
        <h1>Our Courses</h1>
        <!-- <h1>{% blocktrans %} Our Courses {% endblocktrans %}</h1> -->
    </div>
    <hr>

    <p>
        {% blocktrans %} Through our courses we help kids to discover the magic and beauty of technology {% endblocktrans %}
    </p>



    <br/><br/>
    <div class="row">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <img class="card-img-top" src="{{ MEDIA_URL }}/codage.png" alt="">
                <div class="card-body">
                    <h4 class="card-title">{% blocktrans %} Coding {% endblocktrans %}</h4>
                    <p class="card-text">
                        {% blocktrans %} In a fun and enjoyable way kids become familiar with the basic concepts of coding. They are going to discover different interfaces based on visual blocks with drag-and-drop functions where they will develop mini-games and create animations.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'pages:codage' %}" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <img class="card-img-top" src="{{ MEDIA_URL }}/webdesign200x300.png" alt="">
                <div class="card-body">
                    <h4 class="card-title">Web Design</h4>
                    <p class="card-text">This course teaches modern web design techniques, using HTML5 and CSS3</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'pages:webdesign' %}" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <img class="card-img-top" src="{{ MEDIA_URL }}/logoparascolaire.png" alt="">
                <div class="card-body">
                    <h4 class="card-title">Introduction to Python</h4>
                    <p class="card-text">
                        {% blocktrans %} Students will be learn the basic of python, a programming language that is particularly suitable for beginners. They will use their creativity and imagination with the Turtle Graphics module. Students will also develop their writing skills
                        on keyboard, a highly valued skill in programming.{% endblocktrans %}
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'pages:intropython' %}" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

templates/pages/home.html
{% extends 'pages/base.html' %} {% load static %} {% block body %}
<!-- Main page -->
<div class="thumb">
    <img src="{{ MEDIA_URL }}/montana.png" class="imgthumb">
</div>

<section>
    <h2 class="slogan"> Making AI accessible for everyone
    </h2>

</section>


<div class="container-home">
    <section class="intro">
        <h2 class="section-title">What we do ?</h2>

        <hr>
        <p>
            Jumahes is a programming school. For us learn to code is not about vocation but a required skill in order to understand how our world works.
        </p>

        <h2 class="section-title">Why learn to code?</h2>

        <hr>
        <p>
            Computers are part of our everyday life, we use them to surf the internet, do a Google search, see pictures, read e-mails, play games or write text. But how they do all of this? Is it magic? Yes, it's magic. A magic called coding or programming.
        </p>

        <h2 class="section-title">Positive aspects</h2>

        <hr>
        <p>
            Programming is an activity that:
        </p>
        <div id="mylist">
            <ul>
                <li>Stimulates creativity</li>
                <li>Promotes collaboration</li>
                <li>Develops rigor, patience and perseverance</li>
                <li>It trains a logical thinking to solve problems</li>

            </ul>
        </div>
        <br/><br/>
    </section>
</div>
<!-- /.container -->

{% endblock %}


<!-- /.row -->

templates/pages/intropython.html
{% extends 'pages/base.html' %} {% load static %} {% block body%}

<div class="container page">
    <section>

        <h2>Introduction to Python</h2>
        <p>
        </p>
    </section>
</div>
{% endblock %}

templates/pages/training.html
{% extends 'pages/base.html' %} {% load static %} {% block body%}

<div class="container">
    <section>
        <h2 class="section-title">Training</h2>
        <p>
            In-House Training Bring our training to your office. All courses can be tailored to your business’s requirements, whether those are regarding timing, content or anything else. We design and develop all our courses, and can make business-specific additions
            according to the needs of your staff and organisation. As one of the leading on-site and in-house training providers, we have over 8 years' experience of serving corporate clients with bespoke solutions that help their businesses become more
            efficient and more profitable.
        </p>
    </section>
</div>
{% endblock %}

templates/pages/translate.html
{% load i18n %}
{% load static %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{% url 'pages:education' %}" /> <!-- {{ redirect_to }} -->
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" />
</form>

templates/pages/webdesign.html
{% extends 'pages/base.html' %} {% load static %} {% block body%}

<div class="container page">
    <section>

        <h2>Web design</h2>
        <p>
        </p>
    </section>
</div>

{% endblock %}

templates/pages/workshop.html
{% extends 'pages/base.html' %} {% load static %} {% load i18n %} {% block body%}

<div class="container">
    <section>
        <h3>
            Android app development using MIT App Inventor
        </h3>
        <div class="workshop">
            <img src="{{ MEDIA_URL }}/MITappInventor.jpg" class="mit-image">
        </div>
        <p>
            <strong>Description:</strong>
        </p>

        <p>
            {% blocktrans %} Joint us to learn how to create your first mobile app. With {% endblocktrans %}
            <a href="https://appinventor.mit.edu/" target="_blank" title="MIT app inventor">
                
                MIT App Inventor
            </a> ,{% blocktrans %}a programming environment based on visual blocks with drag-and-drop functions, app development becomes easy and fun to learn. Everyone, even kids can develop apps for smartphones and tablets. In this workshop
            we are going to guide you through how to use APP Inventor to build an app from scratch. {% endblocktrans %}
        </p>
        <p>
            <strong>Participants:</strong>
        </p>
        <p> Kids from 12 to 18 years old. This workshop has a LIMITED number of seats available (10).</p>
        <p>
            <strong>Requirements:</strong>
        </p>
        <div id="mylist">
            <ul>
                <li>Basic computer skills </li>
                <li>A laptop, if you do not have a laptop please contact the organizers.</li>
                <li>An Android phone or tablet (optional) </li>

            </ul>
        </div>

        <p>
            <strong>Date and Time:</strong>
        </p>
        <p>On April 14th - 17th from 9:00 a.m to 12:00 p.m</p>

        <p>
            <strong>Venue:</strong>
        </p>
        <p>
            <strong>Price:</strong> Free
        </p>

        <p>
            <strong>Sponsors:</strong>
        </p>
        <p>
            <strong>Register Here</strong>
        </p>


    </section>
</div>
{% endblock %}